version: '3'

services:
  dsurance-postgres:
    image: postgres:12.8
    container_name: dsurance-db
    ports:
      - '5440:5432'
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_USER: 'api'
      POSTGRES_PASSWORD: 'api'
      POSTGRES_DB: 'dsurance'
  dsurance-test-db:
    image: postgres:12.8
    container_name: dsurance-test-db
    ports:
      - '5441:5432'
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_USER: 'api'
      POSTGRES_PASSWORD: 'api'
      POSTGRES_DB: 'test'
  
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.0.1'
    ports:
      - 32182:32182
    environment:
      ZOOKEEPER_CLIENT_PORT: 32182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
  kafka:
    image: 'confluentinc/cp-kafka'
    depends_on:
      - zookeeper
    ports:
      - 29096:29096
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32182
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9096,PLAINTEXT_HOST://localhost:29096
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui
    depends_on:
      - kafka
    ports:
      - '8080:8080'
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9096
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:32182
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
volumes:
  dsurance-postgres: